### ISSUE TITLE
UPDATE: This is a CCL bug! Manual set priorities disabled on load (Alpha 14)

### ISSUE THREAD

**Issue by mordang7** [FluffierThanThou/Fluffy_Tabs#24]
Whenever a save is loaded, the work tab keeps going back to the on/off priorities style instead of the manual style. This started happening for me after installing the latest CCL v0.14.3.1 (maybe even on 0.14.3 not 100% sure). Disabling all other mods, with CCL and Work Tab only active, this still happened even though I saved while the worked tab was on manual.

UPDATE: It appears this is a CCL bug and not Fluffy's.

**Comment by FluffierThanThou** [comment]
Those are the best kind of bugs!
