### ISSUE TITLE
EPOE screws up dwarf therapist colonist list

### ISSUE THREAD

**Issue by RenaudF** [FluffierThanThou/Fluffy_Tabs#3]
Only one or two colonists appears at a time in the list.
Sorting actions will update the list  but still only one or two colonists are displayed at a time.
All colonists stand idly (don't move) and do nothing.
Reverting to normal work tab makes everyone working again.

I have loads of other mods loaded but that only happened after trying to add EPOE on a save.

**Comment by RenaudF** [comment]
![image](https://cloud.githubusercontent.com/assets/2182524/15980476/c53249c6-2f63-11e6-8736-61f5411d7403.png)

**Comment by FluffierThanThou** [comment]
This used to be the result of adding mods without starting a new save game. Should be properly handled as of 14.0.3.

As a general note, don't add mods to existing save games, or if you do - expect them to fail in unexpected ways.
