### ISSUE TITLE
no manager work

### ISSUE THREAD

**Issue by TheMilso** [FluffierThanThou/Fluffy_Tabs#4]
When using the dwarf therapist there is no manager option for colony manager

**Comment by retep998** [comment]
Isn't dwarf therapist for Dwarf Fortress, not RimWorld?

**Comment by TheMilso** [comment]
I'm refering the the advanced work tab that is in beta.

**Comment by FluffierThanThou** [comment]
it should be the rightmost row, note that it might get cut off a bit, so it might read 'mana'. (this is a Unity bug, not much I can do about that)
